### ISSUE TITLE
Parity doesn't compile on macOS 10.13

### ISSUE THREAD

**Issue by Varunram** [paritytech/parity#8254]
> I'm running:
>
> - **Which Parity version?**: https://github.com/paritytech/parity/commit/6e49ff1d98cdcc52733f9ea93dd95a6d487b3279
> - **Which operating system?**: macOS
> - **How installed?**: from source
> - **Did you try to rebuild?**: yes

Expected behaviour: Parity builds
Actual behaviour: 
```
error[E0599]: no method named `eq_ignore_ascii_case` found for type `std::string::String` in the current scope
  --> /Users/varunramg/.cargo/git/checkouts/jsonrpc-22a65938f7d26b63/06bec6a/server-utils/src/matcher.rs:31:19
   |
31 |    None => self.1.eq_ignore_ascii_case(s),
   |                   ^^^^^^^^^^^^^^^^^^^^
   |
   = help: items from traits can only be used if the trait is in scope
   = note: the following trait is implemented but not in scope, perhaps add a `use` for it:
           candidate #1: `use std::ascii::AsciiExt;`

error: aborting due to previous error
```

**Comment by Varunram** [comment]
Oops, turned out my rust version was out of date. Closing.
