### ISSUE TITLE
Cargo build failed due to using app_dirs with rustc 1.26.0-nightly

### ISSUE THREAD

**Issue by rleungx** [paritytech/parity#8267]
```
   Compiling subtle v0.5.1
   Compiling interleaved-ordered v0.1.1
   Compiling app_dirs v1.1.1
error[E0282]: type annotations needed
  --> /Users/Ryan/.cargo/registry/src/github.com-1ecc6299db9ec823/app_dirs-1.1.1/src/imp/platform/macos.rs:10:40
   |
10 |         Ok(Component::RootDir.as_ref().into())
   |                                        ^^^^ cannot infer type for `T`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0282`.
error: Could not compile `app_dirs`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

```
$ rustc -V
rustc 1.26.0-nightly (e5277c145 2018-03-28)
```

It seems that app_dirs doesn't work with both the stable and the nightly Rust.
AndyBarron/app-dirs-rs#28

**Comment by rleungx** [comment]
Also `ntp` can not work with rustc 1.26.0-nightly. See JeffBelgum/ntp#12.
It might need to wait until rustc fixes nightly.

**Comment by rleungx** [comment]
Since the rust team has fixed this, close for now.
